### ISSUE TITLE
Issues with my 64x64 Panel from adafruit

### ISSUE THREAD

**Issue by infinite0007** [adafruit/rpi-fb-matrix#12]
I tried a lot of setting on the config but still can`t figure out why the panel is buggy.
I bought a 64x64 Matrix from adafruit for a school project.
When I´m trying to change that I only have one panel means a chain length of 1 It´s say that error:

![image](https://user-images.githubusercontent.com/50872737/117040367-19db1b00-ad0a-11eb-9f78-6b1c898b07ab.png)

(Changing the panel width/height of each panel doesn`t work either.)

With a chain-standard of 4 the panel window test looks like that:
![panel1](https://user-images.githubusercontent.com/50872737/117042833-c0c0b680-ad0c-11eb-8cf0-408f9d038751.jpg)

![panel2](https://user-images.githubusercontent.com/50872737/117040866-a08ff800-ad0a-11eb-9ff7-53053767f73b.jpg)

I absolutely know that something went wrong but don`t know exactly what.
Anyone got an answer?

**Comment by ladyada** [comment]
hi check
https://learn.adafruit.com/adafruit-rgb-matrix-plus-real-time-clock-hat-for-raspberry-pi/driving-matrices#step-2982866
follow the guide only/exactly:
https://learn.adafruit.com/adafruit-rgb-matrix-plus-real-time-clock-hat-for-raspberry-pi/driving-matrices#step-6-log-into-your-pi-to-install-and-run-software-1745233-16
https://learn.adafruit.com/adafruit-rgb-matrix-plus-real-time-clock-hat-for-raspberry-pi/driving-matrices#testing-the-examples-2982010-30
post any results to the adafruit forums.
