### ISSUE TITLE
Unable to open primary display!

### ISSUE THREAD

**Issue by josh1hart** [adafruit/rpi-fb-matrix#13]
Running the display test works flawlessly. All panels are showing up and working together but when running rpi-fb-matrix, the error message Unable to open primary display! is given.

**Comment by josh1hart** [comment]
![IMG_4172](https://user-images.githubusercontent.com/57352086/145045246-84664638-3268-45fe-a08c-0811fb544ca6.jpg)

**Comment by davemaster** [comment]
Greetings,

Are You running that from a vnc client or from the raspberry terminal?

Share your matrix.cfg

**Comment by davemaster** [comment]
Also try to re-compile the entire rpi-fb-matrix: 

make clean
make all

**Comment by josh1hart** [comment]
[matrix.txt](https://github.com/adafruit/rpi-fb-matrix/files/7669115/matrix.txt)

Thank you for your help and pardon me but I'm learning as I go, vnc? I am running the code and boards all from the raspberry pi. Ill give make clean and all a go now.

**Comment by josh1hart** [comment]
The make clean and all doesn't seem to have worked.
![IMG_4173](https://user-images.githubusercontent.com/57352086/145050781-5d810bb9-6f3d-49f7-a077-d2431c00079f.jpg)

**Comment by josh1hart** [comment]
![IMG_4174](https://user-images.githubusercontent.com/57352086/145051258-cc59a9b7-9c9c-4a04-9eb1-74af5c5456dc.jpg)

Could the fact the HDMI from the raspberry pi is HDMI to VGA? I couldn't see why this could be an issue.

**Comment by davemaster** [comment]
After a lot of time, I plug my 3x2 screen (32x32) using electrodragon active board (3 parallel chains); bullseye installed, and CAN'T access to display...

Researching, the change of display management in Raspberry Pi OS bullseye is guilty, we're fried (that, or learn how to ask for permission to use display, using lightdrm).... better, return to Raspbian OS Buster... no other solution for now

Best regards

**Comment by josh1hart** [comment]
Thank you, This has solved the issue. Simply moving over to buster.
